### ISSUE TITLE
zrtp_isEnrollmentMode always false

### ISSUE THREAD

**Issue by Sn0wfreezeDev** [wernerd/ZRTP4PJ#13]
Hello, 

I built the ZRTP4PJ version for iOS. It all runs perfectly and I don't have problems accepting any SAS keys from other partys. Only when I try to sign the SAS of a PBX enrollment it does not work correctly. 
When I try to check the state of the enrollment mode by using `int32_t zrtp_isEnrollmentMode(ZrtpContext* zrtpContext);`  it always returns 0.

Do I use the wrong method or is there a different problem ? 

I am using the setup code from the simple_pjsua.c file. 

```C
pjmedia_transport* on_create_media_transport(pjsua_call_id call_id,
                                             unsigned media_idx,
                                             pjmedia_transport *base_tp,
                                             unsigned flags)
{
    pjmedia_transport *zrtp_tp = NULL;
    pj_status_t status;
    pjmedia_endpt* endpt = pjsua_get_pjmedia_endpt();
    
    PJ_LOG(3,(THIS_FILE, "ZRTP transport created"));
    status = pjmedia_transport_zrtp_create(endpt, NULL, base_tp,
                                           &zrtp_tp, flags);
    usercb.userData = zrtp_tp;
    
    /* this is optional but highly recommended to enable the application
     * to report status information to the user, such as verfication status,
     * SAS code, etc
     */
    pjmedia_transport_zrtp_setUserCallback(zrtp_tp, &usercb);
    
    /*
     * Initialize the transport. Just the filename of the ZID file that holds
     * our partners ZID, shared data etc. If the files does not exists it will
     * be created an initialized.
     */
    pjmedia_transport_zrtp_initialize(zrtp_tp, "simple.zid", PJ_TRUE);
    return zrtp_tp;
}
```

```Objective-C
static void showSAS(void* data, char* sas, int32_t verified)
{
// Getting the context from a pointer saved to the transport 
    ZrtpContext* context = pjmedia_transport_zrtp_getZrtpContext(zrtp_tp);
// Check for MitM Mode, returns 0
    enrollment = pjmedia_transport_zrtp_isMitmMode(zrtp_tp);
//Check for enrollment mode, returns 0
    int32_t e = zrtp_isEnrollmentMode(context);
    
    if (!verified) {
        if (enrollment) {
// Objective - C code for handling everything else 
            NSLog(@"------------------\n ENROLLMENT \n -------------------");
            [[CallManager sharedManager] zrtpWithSAS:[NSString stringWithCString:sas encoding:NSUTF8StringEncoding] enrollment:YES];
        }else  {
            [[CallManager sharedManager] zrtpWithSAS:[NSString stringWithCString:sas encoding:NSUTF8StringEncoding] enrollment:NO];
        }
        
    }
    
    
   
    PJ_LOG(3,(THIS_FILE, "SAS data: %s, verified: %d \n UserData: %@", sas, verified, data));
}
```

**Comment by wernerd** [comment]
Because PBX handling is a potential security hole (it's MitM) this code is not
compiled by default. You have to enable this code during compilation, set a

#define ZRTP_SAS_RELAY_SUPPORT

or an appropriate compiler flag (-D ZRTP_SAS_RELAY_SUPPORT)

Then it depends if you develop a client or the PBX service application.

First: what do you mean with "sign the SAS of a PBX enrollment"? Do you like
to sign a SAS with a certificate or do you like to accept a PBX trusted MitM
enrollement?


On the client you have to enable the "trusted MitM handling" mode during run-time
before you call 'zrtp_initializeZrtpEngine(...)'. This is a custom configuration
and you have to setup this configuration:

First initialize a ZRTP configuration:
	zrtp_InitializeConfig (ZrtpContext* zrtpContext)
	zrtp_setStandardConfig(ZrtpContext* zrtpContext)

Once done then inform the ZRTP stack to accept trust MitM handling:
	zrtp_setTrustedMitM(zrtpContext, true);

After this is done you call 'zrtp_initializeZrtpEngine(...)' to initialize the
ZRTP stack with the custom configuration.

In case a PBX requestes a trutest MitM enrollment the ZRTP stack calls the app
via the callback function "zrtp_zrtpAskEnrollment(context, EnrollmentRequest)"

Then the client needs to present this request to the user and if the user confirms
then tha app must inform the ZRTP stack to either permit or deny the request during
the call using the "zrtp_acceptEnrollment(ZrtpContext* zrtpContext, int32_t accepted)"
function. The ZRTP stack stores this data/decision for further calls.


On the PBX this a more complex handling. The functions zrtp_setEnrollmentMode(...)
and zrtp_isEnrollmentMode(...) are for PBX ZRTP applications. This PBX will act
as the truested MitM. A PBX app shall set this mode only if the user calls the
specific 'enrollement service' on the PBX.

Which PBX do you use?


Werner

Am 05.11.2015 um 00:59 schrieb Sn0wfreezeDev:
> Hello,
> 
> I built the ZRTP4PJ version for iOS. It all runs perfectly and I don't have problems accepting any SAS keys from other partys. Only when I try to sign the SAS of a PBX enrollment it does not work correctly.
> When I try to check the state of the enrollment mode by using |int32_t zrtp_isEnrollmentMode(ZrtpContext* zrtpContext);| it always returns 0.
> 
> Do I use the wrong method or is there a different problem ?
> 
> I am using the setup code from the simple_pjsua.c file.
> 
> pjmedia_transport* on_create_media_transport(pjsua_call_id call_id,
>                                              unsigned media_idx,
>                                              pjmedia_transport *base_tp,
>                                              unsigned flags)
> {
>     pjmedia_transport *zrtp_tp = NULL;
>     pj_status_t status;
>     pjmedia_endpt* endpt = pjsua_get_pjmedia_endpt();
> 
>     PJ_LOG(3,(THIS_FILE, "ZRTP transport created"));
>     status = pjmedia_transport_zrtp_create(endpt, NULL, base_tp,
>                                            &zrtp_tp, flags);
>     usercb.userData = zrtp_tp;
> 
>     /* this is optional but highly recommended to enable the application
> * to report status information to the user, such as verfication status,
> * SAS code, etc
> */
>     pjmedia_transport_zrtp_setUserCallback(zrtp_tp, &usercb);
> 
>     /*
> * Initialize the transport. Just the filename of the ZID file that holds
> * our partners ZID, shared data etc. If the files does not exists it will
> * be created an initialized.
> */
>     pjmedia_transport_zrtp_initialize(zrtp_tp, "simple.zid", PJ_TRUE);
>     return zrtp_tp;
> }
> 
> static void showSAS(void* data, char* sas, int32_t verified)
> {
> // Getting the context from a pointer saved to the transport
>     ZrtpContext* context = pjmedia_transport_zrtp_getZrtpContext(zrtp_tp);
> // Check for MitM Mode, returns 0
>     enrollment = pjmedia_transport_zrtp_isMitmMode(zrtp_tp);
> //Check for enrollment mode, returns 0
>     int32_t e = zrtp_isEnrollmentMode(context);
> 
>     if (!verified) {
>         if (enrollment) {
> // Objective - C code for handling everything else
>             NSLog(@"------------------\n ENROLLMENT \n -------------------");
>             [[CallManager sharedManager] zrtpWithSAS:[NSString stringWithCString:sas encoding:NSUTF8StringEncoding] enrollment:YES];
>         }else  {
>             [[CallManager sharedManager] zrtpWithSAS:[NSString stringWithCString:sas encoding:NSUTF8StringEncoding] enrollment:NO];
>         }
> 
>     }
> 
> 
> 
>     PJ_LOG(3,(THIS_FILE, "SAS data: %s, verified: %d \n UserData: %@", sas, verified, data));
> }
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/wernerd/ZRTP4PJ/issues/13>.
> 

-- 
Werner Dittmann
email: Werner.Dittmann@t-online.de
cell:  +49 173 44 37 659
PGP key: 82EF5E8B

**Comment by Sn0wfreezeDev** [comment]
Thank you very much ! 

I didn't saw that earlier. We are building a client only App so there is no need for a server PBX. 
Your description, what we have to do, to accept the enrollment on the client side was excellent. 

Have a great week ! 

Alex
